= Edition de vidéo de basket

Le but de ce projet est de produire des outils pour faire des montages de vidéos de matchs de basket.

On trouve:

* Un lecteur: pour visualiser et noter les moments important d'un match.
* Un générateur de vidéo: qui va construite les vidéos à partir d'une liste de moments importants.
* Des scripts: pour faire de l'incrustation d'image, de texte, ...
* Un détecteur de panier: permet de répérer les moments où un panier a potentiellement été marqué.


== Environnement

Le répertoire `docker` contient un `Dockerfile` permettant de construire un environnement de développement.




Prérequis:
----
sudo apt intall magick
pip install moviepy
pip install scipy

pip install keyboard
----

== Ressources


* https://www.stackbuilders.com/blog/python-video-generation/
* https://zulko.github.io/moviepy/getting_started/compositing.html

== Test

On passe par un script qui exécute les tests dans un contenaire Docker.

----
. ./script/run_pytest.sh video_editing/
----

== Execution

----
python3 video_editing/video_generator.py score [MATCH FOLDER]
----

.Format du fichier CSV
----
[POINT];[EQUIPE A ou B];[TEMPS];[Quart temps] ; [Commentaire]
----

----
python3 video_generator.py [COMMAND] [MATCH FOLDER]
----

.Commands
- csv: initialise les fichiers CSV.
- validate: Pour vérifier que les fichiers sont corrects.
- score: Pour visualiser le score.
- generate: Génère les vidéos avec incrustation du score
- highlight: Génère une vidéo de tous les paniers, une des paniers de Sainte Luce, une avec les paniers et lancés francs. 
- quarter: Génère une vidéo par quart-temps.
- half: Génère une vidéo par mi-temps.
- all: Génère une seule vidéo de tout le match.
- full: Génère les vidéos, les highlights et une vidéo par quart temps.

== Steps

.Préparation
- Créer un répertoire `Match_[ANNEE]_[MOIS]_[JOUR]`
- Créer les sous-répertoire `video` et `csv`
- Construire les vidéo avec incrustation du logo avec le script `. ./insert_logo.sh Match_[ANNEE]_[MOIS]_[JOUR]`

.Repérage
- Aller dans le répertoire `Match_[ANNEE]_[MOIS]_[JOUR]`


- Construire les fichiers `CSV` en exécutant la commande `python3 ../video_reader/reader.py -s $(python3 ../video_generator.py final_score . | tail -1) -v video/[NOM VIDEO].mp4` sur chaque fichier video
- Modifier le nom des équipes dans le fichier `video_generator.py` au début du `main`.
- Vérifier le score: `python3 ../video_generator.py score .`

.Génération
- Générer les fichiers .ass : `python3 ../video_generator.py generate .`
- Construire les vidéo avec incrustation du score avec le script `. ../insert_score.sh .`
- Générer les highlights: `python3 ../video_generator.py highlight .`
- Générer la vidéo du match: `python3 ../video_generator.py all .`
- Compresser les vidéos: ffmpeg -i [VIDEO ENTREE].mp4 -c:v libx265 -x265-params crf=25 [VIDEO SORTIE].mp4
- Partager la vidéo via Wetransfert
- Envoyer un message

Peut on compresser les vidéos plus tôt (pendant l'insertion de logo) ? 
Cela peut se faire pendant le repérage manuel des paniers et peut être sans temps supplémentaire

Evaluer le `crf` adapté (23 par défaut).
Plus il augmente, plus on dégrade la vidéo

== Development

To run tests:

----
python3 -m unittest
----

To run one file:
----
python3 -m unittest test_video_generator.py
----
or
----
python3 test_video_generator.py
----
 
 == FFMPEG

ffmpeg -i INPUT -c:v libx265 -an -x265-params crf=25 OUT.mp4
-an: Disable audio
ffmpeg -i INPUT -c:v libx265 -x265-params crf=25 OUT.mp4


== To cut

Cette commande coupe sans réencoder la vidéo (-c copy).

https://stackoverflow.com/questions/18444194/cutting-multimedia-files-based-on-start-and-end-time-using-ffmpeg

----
ffmpeg -i VID_20241005_160156.mp4 -ss 00:00:10 -t 00:00:15  -c copy cut.mp4 
----

== Ajouter des sous-titrages à un fichier vidéo

Vous pouvez également ajouter des sous-titrages à un fichier vidéo en utilisant FFmpeg. Téléchargez le fichier de sous-titrage correct pour votre vidéo et ajoutez-le comme indiqué ci-dessous.
1
	
ffmpeg -i input.mp4 -i soutitrage.srt -map 0 -map 1 -c copy  -c:v libx265 -x265-params crf=25 -preset veryfast output.mp4

https://fr.abyssale.com/generate-video/how-to-add-subtitles-to-videos-with-ffmpeg

ffmpeg -i video1.mp4 -vf "subtitles=soutitrage.srt:force_style='Fontsize=20'" -c:a copy -c:v libx264 -crf 23 -preset veryfast output.mp4


https://fr.abyssale.com/generate-video/how-to-change-the-appearances-of-subtitles-with-ffmpeg

ffmpeg -i video1.mp4 -vf "ass=soustitre2.srt:force_style='Alignment=6'" -c:a copy -c:v libx264 -crf 23 -preset veryfast output.mp4
ffmpeg -i video1.mp4 -vf "ass=soustitre2.srt" -c:a copy -c:v libx264 -crf 23 -preset veryfast output.mp4

https://hhsprings.bitbucket.io/docs/programming/examples/ffmpeg/subtitle/ass.html

== Insert image

https://video.stackexchange.com/questions/12105/add-an-image-overlay-in-front-of-video-using-ffmpeg
ffmpeg -i video1.mp4 -i ../../../SLB_Logo_OK_light.jpg -filter_complex "[0:v][1:v] overlay=5:5:enable='between(t,0,20)'" -pix_fmt yuv420p -c:a copy output.mp4
ffmpeg -i video1.mp4 -i ../../../SLB_Logo_OK_light.jpg -filter_complex "[0:v][1:v] overlay=5:5" -pix_fmt yuv420p -c:a copy output.mp4
ffmpeg -i video1.mp4 -i ../../../SLB_Logo_OKpetit_resize.jpg -filter_complex "[0:v][1:v] overlay=5:5" -pix_fmt yuv420p -c:a copy output.mp4

ffmpeg -i video1.mp4 -i ../../../SLB_Logo_OKpetit.png -filter_complex "[0:v][1:v] overlay=5:5:scale=w=320:h=240" -pix_fmt yuv420p -c:a copy output.mp4


ffmpeg -i video1.mp4 -vf "ass=soustitre3.ass" -c:a copy -c:v libx264 -crf 23 -preset veryfast output.mp4



Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Score, Arial,28,&H0000FFFF,&H00FFFF00,&H00303030,&H80000008,-1,0,0,0,100,100,0.00,0.00,1,1.00,2.00, 8 ,30,10,10,0
Style: Team,  Arial,28,&H0000FFFF,&H00FFFF00,&H00303030,&H80000008,-1,0,0,0,100,100,0.00,0.00,1,1.00,2.00, 8 ,30,10,10,0

Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Alignment, MarginL, MarginR, MarginV, Encoding
Style : Score,Britannic Bold,32,&H0000FFFF,&H00FFFF00,&H00303030,&H99000000,-1,0,6,30,10,10,0
Style : Team,Britannic Bold,48,&H0000FFFF,&H00FFFF00,&H00303030,&H99000000,-1,0,6,30,10,10,0


== Filter voice

https://stackoverflow.com/questions/21659207/filter-out-voice-frequency-with-ffmpeg

What you're looking for is the bandreject filter I suppose:

ffmpeg -i song.wav -c:a pcm_s16le -af "bandreject=f=900:width_type=h:w=600" out.wav -y

This command attenuates everything between 900 - 600 = 300 Hz and 900 + 600 = 1500 Hz.For some reason the width value can't be higher than 999 Hz... Bear in mind that the attenuation is not perfect so if you want more attenuation you can chain the filter as many time as you want:

ffmpeg -i song.wav -c:a pcm_s16le -af "bandreject=f=900:width_type=h:w=600, bandreject=f=900:width_type=h:w=600" out.wav -y

https://steemit.com/audio/@manero666/ffmpeg-apply-a-filter-to-enhance-voice-by-removing-low-and-high-frequency-noises
ffmpeg -i MatchX/video/VID_20241005_164132.mp4 -af lowpass=3000,highpass=200 MatchX/output/out.mp4
