= Edition de vidéo de basket

Le but de ce projet est de produire des outils pour faire des montages de vidéos de matchs de basket.

On trouve:

* Un lecteur: pour visualiser et noter les moments important d'un match.
* Un générateur de vidéo: qui va construite les vidéos à partir d'une liste de moments importants.
* Des scripts: pour faire de l'incrustation d'image, de texte, ...
* Un détecteur de panier: permet de répérer les moments où un panier a potentiellement été marqué.


== Environnement

L'environnement est configuré via `https://direnv.net/[direnv]` et `https://www.jetify.com/docs/devbox/[devbox]`.

S'ils sont installés sur la machine, ils se chargeront de mettre en place l'environnement.

.Installation de `https://www.jetify.com/docs/devbox/[devbox]` et `https://direnv.net/[direnv]`
----
sudo apt  install direnv
curl -fsSL https://get.jetify.com/devbox | bash
----

NOTE: Il peut-être nécessaire de lancer `python` avec un `sudo` car les librairies paratgées peuvent ne pas être accessibles sous `devbox`.

Problème sur imshow avec opencv
---- 
sudp apt-get install libopencv-dev
----

=== Installation manuelle

Voici les prérequies, si vous souhaitez faire une installation sur votre environnement:

----
Python==3.13
include::requirements.txt[]
python3-tk==3.10.8
----


=== Utilisation avec Docker

Le répertoire `docker` contient un `Dockerfile` permettant de construire un environnement de développement.

include::docker/readme.adoc[leveloffset=+3]

== Ressources

* https://www.stackbuilders.com/blog/python-video-generation/
* https://zulko.github.io/moviepy/getting_started/compositing.html

== Test

Depuis les sous-répertoires des projets (`video_editing`, `video_reader`), vous pouvez exécuter les tests avec la commande:
----
pytest
----

== Execution

----
python3 video_editing/video_generator.py score [MATCH FOLDER]
----

.Format du fichier CSV
----
[POINT];[EQUIPE A ou B];[TEMPS];[Quart temps] ; [Commentaire]
----

----
python3 video_generator.py [COMMAND] [MATCH FOLDER]
----

.Commands
- csv: initialise les fichiers CSV.
- validate: Pour vérifier que les fichiers sont corrects.
- score: Pour visualiser le score.
- generate: Génère les vidéos avec incrustation du score
- highlight: Génère une vidéo de tous les paniers, une des paniers de Sainte Luce, une avec les paniers et lancés francs. 
- quarter: Génère une vidéo par quart-temps.
- half: Génère une vidéo par mi-temps.
- all: Génère une seule vidéo de tout le match.
- full: Génère les vidéos, les highlights et une vidéo par quart temps.


== Etapes

.Prérequis
- La variable `TOOLPATH` pointe sur la racine des outils de manipulation des vidéos.
- La variable `LOGO_PATH` pointe sur l'image du logo à insérer.

.Préparation
- Créer un répertoire `Match_[ANNEE]_[MOIS]_[JOUR]`
- Créer les sous-répertoire `video` et `csv`
- Positionner la variable `MATCH` avec la commande `MATCH=$(realpath Match_[ANNEE]_[MOIS]_[JOUR])`
- Mettre les vidéos du match dans le répertorie `video`
- Aller dans le répertoire `Match_[ANNEE]_[MOIS]_[JOUR]`
- Construire les vidéo avec incrustation du logo avec le script `$TOOLPATH/script/insert_logo.sh . $LOGO_PATH`

.Auto détection des paniers
- En construction...

.Repérage
- Construire les fichiers `CSV` en exécutant la commande `python3 $TOOLPATH/video_reader/reader.py -s $(python3 ../video_generator.py final_score . | tail -1) --video video/[NOM VIDEO].mp4` sur chaque fichier video
`python $TOOLPATH/video_reader/reader.py -s $(python ../video_generator.py final_score . | tail -1) --video video/[NOM VIDEO].mp4` 
- Modifier le nom des équipes dans le fichier `video_generator.py` au début du `main`.
- Vérifier le score: `python3 ../video_generator.py score .`

.Génération
- Générer les fichiers .ass : `python $TOOLPATH/video_editing/video_generator.py generate .`
- Construire les vidéo avec incrustation du score avec le script `$TOOLPATH/script/insert_score.sh .`
- Générer les highlights: `python3 ../video_generator.py highlight .`
- Générer la vidéo du match: `python3 ../video_generator.py all .`
- Compresser les vidéos: ffmpeg -i [VIDEO ENTREE].mp4 -c:v libx265 -x265-params crf=25 [VIDEO SORTIE].mp4
- Partager la vidéo via Wetransfert
- Envoyer un message

Peut on compresser les vidéos plus tôt (pendant l'insertion de logo) ? 
Cela peut se faire pendant le repérage manuel des paniers et peut être sans temps supplémentaire

Evaluer le `crf` adapté (23 par défaut).
Plus il augmente, plus on dégrade la vidéo

== Development

To run tests:

----
python3 -m unittest
----

To run one file:
----
python3 -m unittest test_video_generator.py
----
or
----
python3 test_video_generator.py
----

.Class vs static:
* https://www.geeksforgeeks.org/python/class-method-vs-static-method-python/
* https://peps.python.org/pep-0673/

.Check type
----
clear;mypy video_editing/video_match.py --strict
----

or 

----
devbox run check
----